# Generated by Django 5.2.7 on 2025-11-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="contact_view", max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("viewed", "View Event"), ("created", "Create Event")],
                        default="viewed",
                        max_length=50,
                    ),
                ),
                ("object_id", models.IntegerField(blank=True, default=-1)),
                (
                    "model_name",
                    models.CharField(default="contacts.content", max_length=200),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
