# Generated by Django 5.2.7 on 2025-11-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("viewed", "View Event"),
                    ("created", "Create Event"),
                    ("save", "Save or Update Event"),
                ],
                default="viewed",
                max_length=50,
            ),
        ),
    ]
