# Generated by Django 5.2.7 on 2025-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown Event"),
                    ("viewed", "View Event"),
                    ("created", "Create Event"),
                    ("save", "Save or Update Event"),
                ],
                default="viewed",
                max_length=50,
            ),
        ),
    ]
