# Generated by Django 5.2.7 on 2025-11-07 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_event_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                help_text="The user who triggered the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="myevents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
